### ISSUE TITLE
Gene names of the datasets in cancer_benchmark

### ISSUE THREAD

**Issue by RuijieYin** [padilha/biclustlib#5]
Hello! I have been using the datasets in cancer_benchmark, just wondering if the genes have names instead of just numbers? Thanks!

**Comment by padilha** [comment]
Hello @RuijieYin. These datasets were collected from the supplementary material of [this paper](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/1471-2105-9-497). After a quick google search, it seems that the supplementary material of the referred paper has been moved to [this link](https://schlieplab.org/Supplements/CompCancer/). I believe it may contain the information that you have been looking for.
